### ISSUE TITLE
"Play as guest" button does not work

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#10]

**Comment by y21** [comment]
I added the "backend" label to it (and to the backend project) since it wont work even if we fixed the frontend part (unless you want to display an error such as "playing as guest is not available for now", should probably have been more clear when submitting the issue).
Here's what I mean: `/app/` requires a `sessionid` GET parameter and sessions only work for users since a session id is stored with a `username` row. We could pass `null` for username, but then we would not be able to differ between guests.

**Comment by y21** [comment]
The guest button works now.

**Comment by DatNightcat** [comment]
It still doesn’t work on the [registration page.](http://blobs-io.glitch.me/register/)

**Comment by y21** [comment]
Oh sorry, I didn't realize you reopened this. I will add the "Play as a guest" on the registration page as well.

**Comment by y21** [comment]
Fixed in https://github.com/blobs-io/blobs.io/commit/31963f5473e1cacf19cce7f31016728084c5c508.
